Repository xun082/create-neat, pull requests merged in 2024-03, with the labels that each got.

#25 ci: 🎡 add a new workflow
  .github/workflows/build.yml
  .github/workflows/code-review.yml
  .github/workflows/lint.yml
  .husky/commit-msg
  README.md
  package.json
  scripts/check_commit_msg.sh
Labels: continuous integration

#46 fix: 🧩 修复创建项目时重名文件删除失败的错误
  packages/core/src/index.ts
  packages/core/src/utils/createApp.ts
  packages/core/src/utils/createAppTest.ts
  packages/core/src/utils/fileController.ts
Labels: bug

#49 feat: add devDependencies install: (#40)
  packages/core/src/utils/createAppTest.ts
  packages/core/src/utils/dependenciesInstall.ts
  packages/core/src/utils/preset.ts
  packages/core/src/utils/select.ts
Labels: good first issue, continuous integration

#50 Feature/readme&preset#43
  README.md
  packages/core/src/index.ts
  packages/core/src/utils/createAppTest.ts
  packages/core/src/utils/createFile.ts
  packages/core/src/utils/createFiles.ts
  packages/core/src/utils/dependenciesInstall.ts
  packages/core/src/utils/preset.ts
  packages/core/src/utils/select.ts
  packages/core/template/README-EN.md
  packages/core/template/README.md
  readme/README-EN.md
Labels: good first issue

#59 fix: 🧩 修复 ci 配置文件错误导致的 ci 失败
  .github/ISSUE_TEMPLATE/Regression.yml
  .github/workflows/code-review.yml
  .github/workflows/lint.yml
  packages/core/package.json
  pnpm-lock.yaml
Labels: bug

#60 Release/1.1
  .github/ISSUE_TEMPLATE/Regression.yml
  .github/workflows/build.yml
  .github/workflows/code-review.yml
  .github/workflows/lint.yml
  .gitignore
  .husky/commit-msg
  CONTRIBUTING.md
  README.md
  contributing/CONTRIBUTING.en.md
  contributing/CONTRIBUTING.zh_CN.md
  package.json
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/utils/createApp.ts
  packages/core/src/utils/fileController.ts
  pnpm-lock.yaml
  scripts/check_commit_msg.sh
Labels: bug, documentation, enhancement, good first issue, continuous integration

#70 feat: 包管理器的安装和镜像源的选择
  .gitignore
  .vscode/settings.json
  packages/core/src/utils/getnpmSource.ts
  packages/core/src/utils/preset.ts
  packages/core/src/utils/select.ts
  pnpm-lock.yaml
  registries.json
Labels: enhancement, good first issue
